name: Dependabot auto-merge
on:
  workflow_run:
    branches:
      - dependabot/go_modules/**
      - dependabot/submodules/**
    types:
      - completed
    workflows:
      - 'Continuous integration'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: gh pr merge --auto --rebase "${{github.event.workflow_run.pull_requests[0].number}}"
